### PR TITLE
reduce the size of the type space

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by AleMorales** [comment]
Why not allow passing `value` or `value_type` through the different wrappers around `Variable`? (i.e. `Parameters`, `DependentVariable`, etc)

**Comment by ChrisRackauckas** [comment]
What do you mean?

**Comment by AleMorales** [comment]
At the moment if I want to create a Parameter without deafult value I do `Parameter(:p)` but if I want it to have a default value I need to do `Variable(:p, :Parameter, 1.0, Float64)`. Not a big deal of course, just thinking whether this was on purpose and I am misinterpreting `value` and `value_type`

**Comment by ChrisRackauckas** [comment]
oh yes, those just need to be functions with default values.

**Pull request merged**
